-- ClearRank Database Schema
-- Designed for PostgreSQL

-- Enable the uuid-ossp extension to generate UUIDs automatically
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. users Table
-- Stores user accounts and secure OAuth tokens for Google Search Console
-- ==========================================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    google_id VARCHAR(255) UNIQUE NOT NULL,
    access_token TEXT NOT NULL,
    refresh_token TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- 2. properties Table
-- Stores the specific websites (GSC Properties) the user is tracking.
-- ==========================================
CREATE TABLE properties (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    site_url VARCHAR(2048) NOT NULL, -- e.g., https://example.com
    last_synced_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign Key Constraint
    -- If a user is deleted, all their properties are also deleted
    CONSTRAINT fk_user
        FOREIGN KEY (user_id) 
        REFERENCES users (id)
        ON DELETE CASCADE,
        
    -- Ensure a user doesn't add the same property twice
    UNIQUE (user_id, site_url)
);

-- ==========================================
-- 3. keywords Table
-- Stores the raw data pulled from the Google Search Console API.
-- ==========================================
CREATE TABLE keywords (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    property_id UUID NOT NULL,
    query VARCHAR(2048) NOT NULL, -- The actual search term
    ranking_url VARCHAR(2048) NOT NULL, -- The page ranking for it
    position DECIMAL(5, 2) NOT NULL, -- Average rank position (e.g. 12.5)
    clicks INTEGER DEFAULT 0,
    impressions INTEGER DEFAULT 0,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign Key Constraint
    -- If a property is deleted, all its associated keywords are deleted
    CONSTRAINT fk_property
        FOREIGN KEY (property_id) 
        REFERENCES properties (id)
        ON DELETE CASCADE
);

-- Index for faster queries filtering by property ID
CREATE INDEX idx_keywords_property_id ON keywords(property_id);

-- ==========================================
-- 4. intent_clusters Table
-- Stores the semantic groups generated by the LLM.
-- ==========================================
CREATE TABLE intent_clusters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    property_id UUID NOT NULL,
    cluster_name VARCHAR(500) NOT NULL, -- e.g., "Fleet Tracking Pricing"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign Key Constraint
    CONSTRAINT fk_intent_property
        FOREIGN KEY (property_id) 
        REFERENCES properties (id)
        ON DELETE CASCADE
);

-- ==========================================
-- 5. cluster_mappings Table (The Cannibalization Detector)
-- A junction table that links keywords to intent_clusters.
-- ==========================================
-- Logic Note: 
-- A single intent_cluster (e.g., "CRM Pricing") can map to multiple keywords 
-- (e.g., "crm costs", "how much is a crm").
-- If the `keywords` linked via this table have *different* `ranking_url` values,
-- that is exactly how the system detects a keyword cannibalization conflict.
-- ==========================================
CREATE TABLE cluster_mappings (
    cluster_id UUID NOT NULL,
    keyword_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Composite Primary Key to prevent duplicate links
    PRIMARY KEY (cluster_id, keyword_id),
    
    -- Foreign Key Constraint linking to intent_clusters
    CONSTRAINT fk_cluster
        FOREIGN KEY (cluster_id) 
        REFERENCES intent_clusters (id)
        ON DELETE CASCADE,
        
    -- Foreign Key Constraint linking to keywords
    CONSTRAINT fk_keyword
        FOREIGN KEY (keyword_id) 
        REFERENCES keywords (id)
        ON DELETE CASCADE
);

-- Index on keyword_id for faster reverse lookups
CREATE INDEX idx_mappings_keyword_id ON cluster_mappings(keyword_id);
